# Generated by Django 4.2.5 on 2023-12-17 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StableMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_text', models.CharField(max_length=2048, verbose_name='Начальный текст')),
                ('eng_text', models.CharField(max_length=2048, verbose_name='Переведенный текст')),
                ('telegram_chat_id', models.CharField(max_length=128, verbose_name='Номер чата телеграм')),
                ('stable_request_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='ID запроса в stable')),
                ('single_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Общая картинка')),
                ('first_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Первая картинка')),
                ('second_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Вторая картинка')),
                ('third_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Третья картинка')),
                ('fourth_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Четвертая картинка')),
                ('answer_sent', models.BooleanField(default=False, verbose_name='Ответ отправлен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stable_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сообщение в stable',
                'verbose_name_plural': 'Сообщения в stable',
            },
        ),
    ]
