# Generated by Django 4.2.5 on 2023-12-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StableAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название акка')),
                ('api_key', models.CharField(max_length=256, verbose_name='Ключ доступа к Stable')),
            ],
            options={
                'verbose_name': 'Аккаунт в stable ',
                'verbose_name_plural': 'Аккаунты stable',
            },
        ),
    ]
