# Generated by Django 4.2.5 on 2023-12-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0002_stableaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablemessage',
            name='message_type',
            field=models.CharField(choices=[('first', 'Первоначальная генерация'), ('u', 'Одно из 4 U-сообщений'), ('upscaled', 'Увеличенное изображение')], default='first', max_length=128, verbose_name='Тип сообщения'),
        ),
    ]
