# Generated by Django 4.2.5 on 2023-12-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0003_stablemessage_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stablemessage',
            name='message_type',
            field=models.CharField(choices=[('first', 'Первоначальная генерация'), ('u', 'Одно из 4 U-сообщений'), ('upscaled', 'Увеличенное изображение'), ('zoom_out', 'Отдалена'), ('vary', 'Изменена')], default='first', max_length=128, verbose_name='Тип сообщения'),
        ),
    ]
