# Generated by Django 4.2.5 on 2023-12-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0004_alter_stablemessage_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StableSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(blank=True, default='juggernaut-xl', max_length=256, null=True, verbose_name='Номер модели')),
                ('seed', models.CharField(blank=True, default='-1', max_length=128, null=True, verbose_name='Сид')),
                ('num_inference_steps', models.CharField(blank=True, default='20', max_length=8, null=True, verbose_name='Число шагов')),
                ('guidance_scale', models.PositiveIntegerField(default=7, verbose_name='Шкала')),
                ('embeddings_model', models.CharField(blank=True, max_length=256, null=True, verbose_name='Связанная модель')),
            ],
            options={
                'verbose_name': 'Настройки stable',
                'verbose_name_plural': 'Настройки stable',
            },
        ),
    ]
