# Generated by Django 4.2.5 on 2023-12-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0005_stablesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stablesettings',
            name='model_id',
            field=models.CharField(blank=True, choices=[('juggernaut-xl', 'Джаггернаут'), ('deliberate-v3', 'Делиберейт')], default='juggernaut-xl', max_length=256, null=True, verbose_name='Номер модели'),
        ),
    ]
