# Generated by Django 4.2.5 on 2023-12-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0006_alter_stablesettings_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablesettings',
            name='negative_prompt',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Негативный промпт'),
        ),
        migrations.AddField(
            model_name='stablesettings',
            name='positive_prompt',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Позитивный промпт'),
        ),
    ]
