# Generated by Django 4.2.5 on 2023-12-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0007_stablesettings_negative_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stablesettings',
            name='negative_prompt',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Негативный промпт'),
        ),
        migrations.AlterField(
            model_name='stablesettings',
            name='positive_prompt',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Позитивный промпт'),
        ),
    ]
