# Generated by Django 4.2.5 on 2023-12-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0008_alter_stablesettings_negative_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablesettings',
            name='algorithm_type',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип алгоритма'),
        ),
        migrations.AddField(
            model_name='stablesettings',
            name='lora_model',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Модель Лора'),
        ),
        migrations.AddField(
            model_name='stablesettings',
            name='lora_strength',
            field=models.FloatField(blank=True, null=True, verbose_name='lora strength'),
        ),
        migrations.AddField(
            model_name='stablesettings',
            name='sampling_method',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Метод семплинга'),
        ),
        migrations.AddField(
            model_name='stablesettings',
            name='scheduler',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='scheduler'),
        ),
    ]
