# Generated by Django 4.2.5 on 2023-12-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0009_stablesettings_algorithm_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablemessage',
            name='height',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='stablemessage',
            name='seed',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Сид'),
        ),
        migrations.AddField(
            model_name='stablemessage',
            name='width',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Ширина'),
        ),
    ]
