# Generated by Django 4.2.5 on 2023-12-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0011_stablemessage_vary_guidance_scale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stablemessage',
            name='vary_guidance_scale',
        ),
        migrations.RemoveField(
            model_name='stablemessage',
            name='vary_num_inference_steps',
        ),
        migrations.RemoveField(
            model_name='stablemessage',
            name='vary_strength',
        ),
        migrations.AddField(
            model_name='stablesettings',
            name='vary_guidance_scale',
            field=models.FloatField(blank=True, null=True, verbose_name='Вариации шкала(7.5)'),
        ),
        migrations.AddField(
            model_name='stablesettings',
            name='vary_num_inference_steps',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Вариации число шагов'),
        ),
        migrations.AddField(
            model_name='stablesettings',
            name='vary_strength',
            field=models.FloatField(blank=True, null=True, verbose_name='Вариации сила картинки'),
        ),
    ]
