# Generated by Django 4.2.5 on 2023-12-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0012_remove_stablemessage_vary_guidance_scale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stablesettings',
            name='lora_strength',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='lora strength'),
        ),
        migrations.AlterField(
            model_name='stablesettings',
            name='model_id',
            field=models.CharField(blank=True, choices=[('juggernaut-xl', 'Джаггернаут'), ('deliberate-v3', 'Делиберейт'), ('sdxl', 'sdxl')], default='juggernaut-xl', max_length=256, null=True, verbose_name='Номер модели'),
        ),
    ]
