# Generated by Django 4.2.5 on 2024-01-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0013_alter_stablesettings_lora_strength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stablesettings',
            name='model_id',
            field=models.CharField(blank=True, default='juggernaut-xl', max_length=256, null=True, verbose_name='Номер модели'),
        ),
    ]
