# Generated by Django 4.2.5 on 2024-01-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0014_alter_stablesettings_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablesettings',
            name='controlnet_model',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='controlnet_model'),
        ),
        migrations.AddField(
            model_name='stablesettings',
            name='controlnet_type',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='controlnet_type'),
        ),
    ]
