# Generated by Django 4.2.5 on 2024-01-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0015_stablesettings_controlnet_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablesettings',
            name='controlnet_conditioning_scale',
            field=models.FloatField(blank=True, null=True, verbose_name='Шкала контролнет'),
        ),
    ]
