# Generated by Django 4.2.5 on 2024-01-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0016_stablesettings_controlnet_conditioning_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stablemessage',
            name='message_type',
            field=models.CharField(choices=[('first', 'Первоначальная генерация'), ('u', 'Одно из 4 U-сообщений'), ('upscaled', 'Увеличенное изображение'), ('zoom_out', 'Отдалена'), ('vary', 'Изменена'), ('double', 'Двойная отправка')], default='first', max_length=128, verbose_name='Тип сообщения'),
        ),
    ]
