# Generated by Django 4.2.5 on 2024-04-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0017_alter_stablemessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablemessage',
            name='new_endpoint',
            field=models.BooleanField(default=False, verbose_name='Новый сервис'),
        ),
    ]
