# Generated by Django 4.2.5 on 2024-05-13 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stable_messages', '0018_stablemessage_new_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(max_length=128, verbose_name='Номер чата телеграм')),
                ('request_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='ID запроса в fireworks')),
                ('initial_image', models.CharField(blank=True, max_length=512, null=True, verbose_name='Картинка-основа')),
                ('video', models.CharField(blank=True, max_length=512, null=True, verbose_name='Сгенерированное видео')),
                ('successfully_generated', models.BooleanField(default=False, verbose_name='Успешно сгенерировано')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Видео сообщение',
                'verbose_name_plural': 'Видео сообщения',
            },
        ),
    ]
