# Generated by Django 4.2.5 on 2024-05-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0019_videomessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomessages',
            name='variables',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Параметры генерации'),
        ),
    ]
