# Generated by Django 4.2.5 on 2024-09-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0020_videomessages_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablemessage',
            name='sent_to_stable',
            field=models.BooleanField(default=False, verbose_name='Отправлено в генерацию'),
        ),
    ]
