# Generated by Django 4.2.5 on 2024-06-15 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stable_messages', '0020_videomessages_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048, verbose_name='Начальный текст')),
                ('telegram_chat_id', models.CharField(max_length=128, verbose_name='Номер чата телеграм')),
                ('stable_request_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='ID запроса в stable')),
                ('single_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Общая картинка')),
                ('first_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Первая картинка')),
                ('second_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Вторая картинка')),
                ('third_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Третья картинка')),
                ('fourth_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Четвертая картинка')),
                ('answer_sent', models.BooleanField(default=False, verbose_name='Ответ отправлен')),
                ('width', models.CharField(blank=True, max_length=8, null=True, verbose_name='Ширина')),
                ('height', models.CharField(blank=True, max_length=8, null=True, verbose_name='Высота')),
                ('seed', models.CharField(blank=True, max_length=16, null=True, verbose_name='Сид')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('message_type', models.CharField(choices=[('first', 'Первоначальная генерация'), ('u', 'Одно из 4 U-сообщений'), ('upscaled', 'Увеличенное изображение'), ('zoom_out', 'Отдалена'), ('vary', 'Изменена'), ('double', 'Двойная отправка')], default='first', max_length=128, verbose_name='Тип сообщения')),
                ('new_endpoint', models.BooleanField(default=False, verbose_name='Новый сервис')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Тестовое сообщение в stable',
                'verbose_name_plural': 'Тестовые сообщения в stable',
            },
        ),
    ]
