# Generated by Django 4.2.5 on 2024-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0021_testmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmessage',
            name='enhanced_style',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Расширенный стиль'),
        ),
    ]
