# Generated by Django 4.2.5 on 2024-07-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0022_testmessage_enhanced_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomessages',
            name='prompt',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Промпт'),
        ),
    ]
