# Generated by Django 4.2.5 on 2024-07-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0023_videomessages_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomessages',
            name='height',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='videomessages',
            name='width',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Ширина'),
        ),
    ]
