# Generated by Django 4.2.5 on 2024-07-03 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0024_videomessages_height_videomessages_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetVideoVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, verbose_name='Юзернейм пользователя')),
                ('is_set', models.BooleanField(default=False, verbose_name='Уже установлено')),
                ('video_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_video_variables', to='stable_messages.videomessages', verbose_name='Сообщение, которому задаем параметры')),
            ],
            options={
                'verbose_name': 'Заявка на установку формата сообщения',
                'verbose_name_plural': 'Заявки на установку формата сообщения',
            },
        ),
    ]
