# Generated by Django 4.2.5 on 2024-07-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0025_setvideovariables'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablemessage',
            name='sent_to_stable',
            field=models.BooleanField(default=True, verbose_name='Запрос на генерацию отправлен'),
        ),
    ]
