# Generated by Django 4.2.5 on 2023-10-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_payment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_payment_expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата истечения платежа'),
        ),
    ]
