# Generated by Django 4.2.5 on 2023-11-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preset',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Суффикс для всех сообщений пользователя'),
        ),
    ]
