# Generated by Django 4.2.5 on 2023-12-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remain_messages',
            field=models.PositiveIntegerField(default=0, verbose_name='Оставшиеся генерации'),
        ),
    ]
