# Generated by Django 4.2.5 on 2023-12-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_remain_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remain_paid_messages',
            field=models.PositiveIntegerField(default=0, verbose_name='Оставшиеся платные генерации'),
        ),
    ]
