# Generated by Django 4.2.5 on 2023-12-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_remain_paid_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remain_messages',
            field=models.PositiveIntegerField(default=10, verbose_name='Оставшиеся генерации'),
        ),
    ]
