# Generated by Django 4.2.5 on 2023-12-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stable_messages', '0002_stableaccount'),
        ('users', '0006_alter_user_remain_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stable_users', to='stable_messages.stableaccount', verbose_name='Аккаунт stable'),
        ),
    ]
