# Generated by Django 4.2.5 on 2024-01-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_stable_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('positive_prompt', models.CharField(max_length=2048, verbose_name='Позитивный промпт')),
                ('negative_prompt', models.CharField(max_length=2048, verbose_name='Негативный промпт')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.style', verbose_name='Стиль'),
        ),
    ]
