# Generated by Django 4.2.5 on 2024-01-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_style_user_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='name_for_menu',
            field=models.CharField(default='Стиль', max_length=128, verbose_name='Название для меню'),
        ),
    ]
