# Generated by Django 4.2.5 on 2024-01-13 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_style_name_for_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(blank=True, default='juggernaut-xl', max_length=256, null=True, verbose_name='Номер модели')),
                ('seed', models.CharField(blank=True, default='-1', max_length=128, null=True, verbose_name='Сид')),
                ('num_inference_steps', models.CharField(blank=True, default='20', max_length=8, null=True, verbose_name='Число шагов')),
                ('guidance_scale', models.PositiveIntegerField(default=7, verbose_name='Шкала')),
                ('embeddings_model', models.CharField(blank=True, max_length=256, null=True, verbose_name='Связанная модель')),
                ('negative_prompt', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Негативный промпт')),
                ('positive_prompt', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Позитивный промпт')),
                ('lora_model', models.CharField(blank=True, max_length=256, null=True, verbose_name='Модель Лора')),
                ('lora_strength', models.CharField(blank=True, max_length=128, null=True, verbose_name='lora strength')),
                ('sampling_method', models.CharField(blank=True, max_length=256, null=True, verbose_name='Метод семплинга')),
                ('algorithm_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип алгоритма')),
                ('scheduler', models.CharField(blank=True, max_length=256, null=True, verbose_name='scheduler')),
                ('vary_num_inference_steps', models.CharField(blank=True, max_length=16, null=True, verbose_name='Вариации число шагов')),
                ('vary_guidance_scale', models.FloatField(blank=True, null=True, verbose_name='Вариации шкала(7.5)')),
                ('vary_strength', models.FloatField(blank=True, null=True, verbose_name='Вариации сила картинки')),
                ('controlnet_model', models.CharField(blank=True, max_length=256, null=True, verbose_name='controlnet_model')),
                ('controlnet_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='controlnet_type')),
            ],
            options={
                'verbose_name': 'Кастомные настройки для пользователя',
                'verbose_name_plural': 'Кастомные настройки для пользователя',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customsettings'),
        ),
    ]
