# Generated by Django 4.2.5 on 2024-01-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customsettings_user_custom_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsettings',
            name='name',
            field=models.CharField(default='Какие-то настройки', max_length=128, verbose_name='Название настроек'),
        ),
    ]
