# Generated by Django 4.2.5 on 2024-01-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customsettings_controlnet_conditioning_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_test_user',
            field=models.BooleanField(default=False, verbose_name='Тестовый пользователь'),
        ),
    ]
