# Generated by Django 4.2.5 on 2024-05-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customsettings_enhance_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remain_video_messages',
            field=models.PositiveIntegerField(default=0, verbose_name='Оставшиеся генерации видео'),
        ),
    ]
