# Generated by Django 4.2.5 on 2024-05-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_remain_video_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_test_video_payment',
            field=models.BooleanField(default=False, verbose_name='Оплачивал тестовые генерации'),
        ),
    ]
