# Generated by Django 4.2.5 on 2024-09-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_used_test_video_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='video_preset',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Суффикс для всех видео сообщений пользователя'),
        ),
    ]
