# Generated by Django 4.2.5 on 2024-10-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_video_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='partner_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='id чата для начисления реферальных'),
        ),
    ]
