# Generated by Django 4.2.5 on 2023-10-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_tariff_cost', models.PositiveIntegerField(default=150, verbose_name='Стоимость дневной подписки')),
                ('month_tariff_cost', models.PositiveIntegerField(default=1000, verbose_name='Стоимость месячной подписки')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
