# Generated by Django 4.2.5 on 2023-12-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='say_hi_video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Приветственное видео'),
        ),
    ]
