# Generated by Django 4.2.5 on 2023-12-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0002_sitesettings_say_hi_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='day_tariff_count',
            field=models.PositiveIntegerField(default=50, verbose_name='Количество генераций при покупке бота на день'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='month_tariff_count',
            field=models.PositiveIntegerField(default=1000, verbose_name='Количество генераций при покупке бота на месяц'),
        ),
    ]
