# Generated by Django 4.2.5 on 2023-12-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0003_sitesettings_day_tariff_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024, verbose_name='Текст уведомления')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
