# Generated by Django 4.2.5 on 2023-12-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0004_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notice_message',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Сообщение для отправки пользователям'),
        ),
    ]
