# Generated by Django 4.2.5 on 2024-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0005_sitesettings_notice_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='say_hi_video_video_bot',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Приветственное видео для видео бота'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='settings_lesson_link',
            field=models.CharField(blank=True, max_length=11024, null=True, verbose_name='Ссылка на урок по настройкам'),
        ),
    ]
