# Generated by Django 4.2.5 on 2024-07-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0006_sitesettings_say_hi_video_video_bot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='queue_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер очереди для отправки сообщений'),
        ),
    ]
