# Generated by Django 4.2.5 on 2024-10-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0006_sitesettings_say_hi_video_video_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='notice_message',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Сообщение для отправки пользователям'),
        ),
    ]
