# Generated by Django 4.2.5 on 2024-07-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0007_sitesettings_queue_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='settings_lesson_link',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ссылка на урок по настройкам'),
        ),
    ]
