# Generated by Django 4.2.5 on 2024-02-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(max_length=256, verbose_name='Логин телеграм')),
                ('telegram_chat_id', models.CharField(max_length=128, verbose_name='ИД чата телеграм')),
                ('telegram_message_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='ИД сообщения телеграм')),
                ('answer_to_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='ИД сообщения, на которое отвечаем')),
                ('message_text', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Текст сообщения')),
                ('image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='ИД картинки, прикрепленной к сообщению')),
                ('answered', models.BooleanField(default=False, verbose_name='Отвечено')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
