# Generated by Django 4.2.5 on 2024-01-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='answered',
            field=models.BooleanField(default=False, verbose_name='Отвечено'),
        ),
    ]
