# Generated by Django 4.2.5 on 2024-01-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportmessage_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='image',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='ИД картинки, прикрепленной к сообщению'),
        ),
    ]
