# Generated by Django 4.2.5 on 2023-11-11 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название курса')),
                ('cover', models.FileField(upload_to='', verbose_name='Обложка курса')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость курса')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность курса, дней')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_date', models.DateField(auto_now_add=True, verbose_name='Дата покупки')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Курс пользователей',
                'verbose_name_plural': 'Курсы пользователей',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название урока')),
                ('cover', models.FileField(upload_to='', verbose_name='Обложка урока')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный')),
                ('finished', models.BooleanField(default=False, verbose_name='Пройден')),
                ('video_url', models.CharField(max_length=1024, verbose_name='Источник видео')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
                ('previous_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_lessons', to='courses.lesson', verbose_name='Предыдущий урок')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('course_id',),
            },
        ),
    ]
