# Generated by Django 4.2.5 on 2023-11-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_is_active_lesson_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='finished',
        ),
        migrations.AddField(
            model_name='usercourses',
            name='finished_lessons',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Пройденные уроки'),
        ),
    ]
