# Generated by Django 4.2.5 on 2023-11-11 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_lesson_finished_usercourses_finished_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourses',
            name='expires_at',
            field=models.DateField(default=datetime.datetime(2023, 11, 11, 17, 1, 48, 368939, tzinfo=datetime.timezone.utc), verbose_name='Срок покупки истекает'),
        ),
    ]
