# Generated by Django 4.2.5 on 2023-11-11 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_usercourses_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourses',
            name='expires_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Срок покупки истекает'),
        ),
    ]
