# Generated by Django 4.2.5 on 2023-11-12 06:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_usercourses_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourses',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание урока'),
        ),
    ]
