# Generated by Django 4.2.5 on 2023-11-12 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_usercourses_expires_at_lesson_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourses',
            name='expires_at',
            field=models.DateField(default=datetime.datetime(2023, 11, 12, 7, 3, 56, 518869, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercourses',
            name='buying_date',
            field=models.DateField(verbose_name='Дата покупки'),
        ),
    ]
