# Generated by Django 4.2.5 on 2023-11-24 16:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_usercourses_expires_at_alter_usercourses_buying_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст к картинке')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Блок урока',
                'verbose_name_plural': 'Блоки уроков',
                'ordering': ('order',),
            },
        ),
    ]
