# Generated by Django 4.2.5 on 2023-11-24 18:27

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lessontextblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True, verbose_name='Видео'),
        ),
    ]
