# Generated by Django 4.2.5 on 2023-11-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lesson_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
    ]
