# Generated by Django 4.2.5 on 2023-11-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lesson_cover_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Источник видео'),
        ),
    ]
