# Generated by Django 4.2.5 on 2023-12-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('course_id', 'order'), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
