# Generated by Django 4.2.5 on 2023-12-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontextblock',
            options={'ordering': ('lesson_id', 'order'), 'verbose_name': 'Блок урока', 'verbose_name_plural': 'Блоки уроков'},
        ),
        migrations.AlterField(
            model_name='lessontextblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
