# Generated by Django 4.2.5 on 2023-12-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontextblock',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='courses.lesson', verbose_name='Урок'),
        ),
    ]
