# Generated by Django 4.2.5 on 2024-03-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prolongation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость курса')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность курса, дней')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prolongations', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Продление курса',
                'verbose_name_plural': 'Продления курсов',
            },
        ),
    ]
