# Generated by Django 4.2.5 on 2023-10-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.PositiveIntegerField(verbose_name='Сумма заказа')),
                ('payment_url', models.CharField(blank=True, max_length=1048, null=True, verbose_name='Платежная ссылка')),
                ('days', models.PositiveIntegerField(verbose_name='Дней для оплаты')),
                ('payment_status', models.CharField(choices=[('Not paid', 'Не оплачен'), ('Paid', 'Оплачен')], default='Not paid', max_length=15, verbose_name='Статус оплаты')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Время оплаты')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
