# Generated by Django 4.2.5 on 2023-12-03 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_lessontextblock_options_and_more'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Дней для оплаты'),
        ),
    ]
