# Generated by Django 4.2.5 on 2024-03-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_prolongation'),
        ('orders', '0004_order_message_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prolongation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='courses.prolongation', verbose_name='Продление'),
        ),
    ]
