# Generated by Django 4.2.5 on 2024-05-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_prolongation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='video_message_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число видео генераций'),
        ),
    ]
