# Generated by Django 4.2.5 on 2023-10-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='Код подтверждения')),
                ('telegram_nick', models.CharField(max_length=256, verbose_name='Ник telegram')),
                ('used', models.BooleanField(default=False, verbose_name='Использован')),
                ('new_message_sent', models.BooleanField(default=False, verbose_name='Отправлено новое сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение с кодом',
                'verbose_name_plural': 'Сообщения с кодом',
            },
        ),
        migrations.CreateModel(
            name='DiscordAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=128, verbose_name='login')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('session_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='session_id')),
                ('channel_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='channel_id')),
                ('last_message_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='ID последнего запрошенного сообщения в акке')),
            ],
            options={
                'verbose_name': 'Аккаунт дискорд для подключения midjourney',
                'verbose_name_plural': 'Аккаунты дискорд для подключения midjourney',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024, verbose_name='Текст сообщения')),
                ('user_telegram', models.CharField(max_length=128, verbose_name='Телега пользователя')),
                ('telegram_id', models.CharField(max_length=64, verbose_name='id telegram пользователя')),
                ('discord_message_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер сообщения в discord')),
                ('images', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Список url вложенных файлов')),
                ('buttons', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Коды кнопок ответа')),
                ('answer_sent', models.BooleanField(default=False, verbose_name='Ответ отправлен')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='DiscordConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=256, null=True, verbose_name='token')),
                ('channel_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Номер канала')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='discord_messages.discordaccount', verbose_name='Соединение с дискордом')),
            ],
            options={
                'verbose_name': 'Соединение с discord',
                'verbose_name_plural': 'Соединения с discord',
            },
        ),
    ]
