# Generated by Django 4.2.5 on 2023-10-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='buttons',
            field=models.JSONField(default={}, verbose_name='Коды кнопок ответа'),
        ),
    ]
