# Generated by Django 4.2.5 on 2023-10-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_messages', '0002_alter_message_buttons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='buttons',
            field=models.JSONField(default=dict, verbose_name='Коды кнопок ответа'),
        ),
    ]
