# Generated by Django 4.2.5 on 2023-10-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_messages', '0004_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='eng_text',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Текст сообщения английский'),
        ),
    ]
