# Generated by Django 4.2.5 on 2023-10-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_messages', '0005_message_eng_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answer_type',
            field=models.CharField(choices=[('start_gen', 'Генерация 4 картинок'), ('upscaled', 'Увеличенная 1 картинка')], default='start_gen', max_length=64, verbose_name='Тип ответа в discord'),
        ),
    ]
