# Generated by Django 4.2.5 on 2023-10-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_messages', '0006_message_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer_type',
            field=models.CharField(choices=[('start_gen', 'Генерация 4 картинок'), ('upscaled', 'Увеличенная 1 картинка'), ('got_seed', 'Можно менять')], default='start_gen', max_length=64, verbose_name='Тип ответа в discord'),
        ),
    ]
