# Generated by Django 4.2.5 on 2023-10-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_messages', '0007_alter_message_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seed',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Сид картинки'),
        ),
    ]
