# Generated by Django 4.2.5 on 2023-10-31 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord_messages', '0008_message_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='initial_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='discord_messages.message', verbose_name='Начальное сообщение'),
        ),
    ]
