# Generated by Django 4.2.5 on 2023-10-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_messages', '0009_message_initial_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='initial_message',
        ),
        migrations.AddField(
            model_name='message',
            name='job',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='JOB сообщения'),
        ),
    ]
