# Generated by Django 4.2.5 on 2023-11-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_messages', '0010_remove_message_initial_message_message_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seed_send',
            field=models.BooleanField(default=False, verbose_name='Сид получен и отправлен'),
        ),
    ]
