# Generated by Django 4.2.5 on 2023-11-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_messages', '0011_message_seed_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='no_ar_text',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Текст сообщения без дефисов'),
        ),
    ]
