# Generated by Django 4.2.5 on 2023-12-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_messages', '0013_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordaccount',
            name='queue_delay',
            field=models.PositiveIntegerField(default=1, verbose_name='Задержка в отправке сообщений'),
        ),
    ]
