# Generated by Django 4.2.5 on 2023-12-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_messages', '0014_discordaccount_queue_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordaccount',
            name='queue_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер очереди'),
        ),
    ]
